# -*- coding: utf-8 -*-
"""Tema 1.2 — What Was Your Previous School Like?"""
from common import *
from common import test_blocks, answer_blocks
from tests_t12 import TESTS

THEME_ID = "1-2"
THEME_TITLE = "What Was Your Previous School Like?"
SCENARIO = "Scenario 1: Our New Classmates"
LUI, ROS, ELE = "am_michael", "af_bella", "af_sarah"
SPEAKERS = {LUI: "Luis", ROS: "Rosa"}

VOCAB = [
    ("previous", "PRÍ-vi-os", "anterior", "My previous school was in Las Tablas."),
    ("old", "OULD", "viejo, antiguo", "The building was very old."),
    ("modern", "MÁ-dern", "moderno", "My new school is modern."),
    ("quiet", "KUÁI-et", "tranquilo, silencioso", "The library was very quiet."),
    ("noisy", "NÓI-si", "ruidoso", "The cafeteria is noisy at lunch."),
    ("classroom", "KLÁS-rum", "salón de clases", "Our classroom was small."),
    ("playground", "PLÉI-graund", "patio de juegos", "We played on the playground."),
    ("garden", "GÁR-den", "huerto, jardín", "My old school had a big garden."),
    ("move (to)", "MUV", "mudarse", "My family moved to Colón."),
    ("used to", "YÚS-tu", "solía, acostumbraba", "I used to walk to school."),
    ("miss", "MIS", "extrañar", "I miss my old friends."),
    ("break", "BREIK", "recreo, descanso", "We had a long break at ten."),
]

READING = [
    "My name is Luis Castillo. Last year, my family moved from Las Tablas to Colón. My previous school was small and old. There were only six classrooms, and every classroom had a big window. The school had a garden, and we planted tomatoes and corn there. I used to walk to school with my cousin, and we talked about soccer all the way.",
    "My new school is bigger and more modern than my old school. It has a computer room and a large library. The cafeteria is the noisiest place in the school! At first, I was nervous because I didn't know anyone. Then a classmate named Rosa helped me find my classroom. Now we are good friends.",
    "I miss my old garden, but I like my new school. Next month, I will join the science club. Maybe we will make a garden here too!",
]

CHANT = [
    "I walked to school, I talked with friends,",
    "I played all day until the end.",
    "I planted beans, I painted a wall,",
    "My old school was the best of all!",
    "Now my school is bigger and new.",
    "I will make friends, and so will you!",
]

DIALOGUE = [
    (ROS, "Hi, Luis! How was your first week?"),
    (LUI, "It was good, thanks. But this school is very big!"),
    (ROS, "What was your previous school like?"),
    (LUI, "It was small and quiet. There were only six classrooms."),
    (ROS, "Only six? Wow! Did you have a library?"),
    (LUI, "No, we didn't. But we had a big garden. We planted tomatoes and corn."),
    (ROS, "That's cool. How did you go to school?"),
    (LUI, "I used to walk with my cousin. Now my mom drives me."),
    (ROS, "Do you like this school?"),
    (LUI, "Yes! The computer room is the best. And next month, I will join the science club."),
    (ROS, "Me too! See you there."),
]

TEST_TALK = [
    "Hi, I'm Elena. I'm from Antón, in Coclé.",
    "My old school was in the countryside, near a river. It was a small school with only forty students.",
    "We had classes from seven to twelve, and then I went home for lunch. Every Friday, we cleaned the school garden together.",
    "Now I study in Penonomé. My new school has five hundred students, so it is much bigger and noisier.",
    "Classes start at seven and finish at one thirty, and we eat lunch in the cafeteria.",
    "The best thing about my new school is the music room. I used to play the guitar alone at home, but now I play in the school band.",
    "Next year, I will be in the school concert!",
]

SPEAK_MODELS = [
    "My previous school was small and quiet.",
    "I used to walk to school.",
    "We planted tomatoes in the garden.",
    "I walked to school with my cousin.",
    "My new school is bigger than my old school.",
    "The library is the quietest place in the school.",
]

SPEAK_TEST_Q = [
    "Question one. What was your previous school like?",
    "Question two. How did you go to school?",
    "Question three. What did you use to do at recess?",
    "Question four. Compare your old school and your new school. Use bigger, smaller, or more modern.",
    "Question five. What will you do next year at school?",
]

TRACKS = [
    {"n": "01", "title": "Vocabulario clave", "instr": "Escucha cada palabra y su ejemplo. Repite en voz alta durante la pausa.",
     "segments": vocab_segments(VOCAB)},
    {"n": "02", "title": "Lectura: My Old School and My New School", "instr": "Escucha el texto mientras lo sigues con el dedo en tu libro.",
     "segments": [(LUI, p, 1.0) for p in READING]},
    {"n": "03", "title": "Chant: My Old School", "instr": "Escucha y repite. Fíjate en cómo suena la -ed: walked /t/, played /d/, planted /ɪd/.",
     "segments": [(NAR, l, 0.5) for l in CHANT]},
    {"n": "04", "title": "Listening — Práctica: Luis and Rosa", "instr": "Escucha el diálogo dos veces. La primera vez, solo escucha. La segunda vez, responde.",
     "segments": [(v, t, 0.6) for v, t in DIALOGUE]},
    {"n": "05", "title": "Listening — Mini-test: Elena", "instr": "Mini-test. Escucha dos veces como máximo y responde en tu libro.",
     "segments": [(ELE, t, 0.7) for t in TEST_TALK]},
    {"n": "06", "title": "Speaking — Oraciones modelo", "instr": "Escucha cada oración y repítela en la pausa. Después grábate y compara.",
     "segments": [(NAR, s, 3.0) for s in SPEAK_MODELS]},
    {"n": "07", "title": "Speaking — Mini-test (examen oral)", "instr": "Activa la grabadora de tu celular. Responde cada pregunta en voz alta durante la pausa.",
     "segments": [(NAR, "Speaking test. Answer each question with complete sentences.", 2.0)] + [(NAR, q, 11.0) for q in SPEAK_TEST_Q]},
]
audio = audio_factory(THEME_ID, TRACKS)

BLOCKS = [
    {"t": "theme_cover", "scenario": SCENARIO, "theme": "Theme 2: " + THEME_TITLE, "es": "¿Cómo era tu escuela anterior?",
     "goals": ["Describir tu escuela anterior con **was / were** y el pasado: *It **was** small. We **planted** corn.*",
               "Hablar de lo que hacías antes con **used to**: *I **used to** walk to school.*",
               "Comparar escuelas: *bigger than, more modern than, the noisiest.*",
               "Pronunciar bien la **-ed** final: walk**ed** /t/, play**ed** /d/, plant**ed** /ɪd/."]},

    H1("¿Te sientes perdido? Empieza aquí"),
    P("Si en clase no entendiste el tema, lee esta página primero. Aquí está **lo esencial** en una sola hoja."),
    H3("1. Las 10 palabras que más vas a escuchar"),
    TABLE([2200, 2700, 2200, 2700], ["Inglés", "Español", "Inglés", "Español"], [
        ["previous", "anterior", "noisy", "ruidoso"],
        ["old", "viejo", "classroom", "salón de clases"],
        ["modern", "moderno", "playground", "patio de juegos"],
        ["quiet", "tranquilo", "move", "mudarse"],
        ["used to", "solía", "miss", "extrañar"],
    ]),
    H3("2. La pregunta del tema y cómo responderla"),
    TABLE([4900, 4900], ["Pregunta", "Respuesta"], [
        ["What **was** your previous school like?", "It **was** small and quiet."],
        ["**Was** it big?", "No, it **wasn't**. It was small."],
        ["**Were** the teachers friendly?", "Yes, they **were**."],
        ["What did you **use to** do at recess?", "I **used to** play soccer."],
    ]),
    H3("3. Las reglas que más se preguntan en las pruebas"),
    P("**Pasado de be:** I / he / she / it **was** · you / we / they **were**"),
    P("**Comparar:** palabra corta + **-er than** (small**er** than) · palabra larga: **more** + palabra + **than** (**more modern** than)"),
    P("**El/la más:** **the** + palabra corta + **-est** (**the** small**est**) · **the most** + palabra larga (**the most** modern)"),
    H3("4. Una descripción modelo"),
    P("*My previous school was small and quiet. I used to walk to school. My new school is bigger and more modern.*"),
    PB,

    H1("1. Vocabulario"),
    P("Escucha el audio, señala cada palabra y repítela en voz alta. La columna **Se pronuncia** es una ayuda aproximada; el audio es la pronunciación correcta."),
    audio("01"),
    TABLE([2100, 1700, 2300, 3700], ["Inglés", "Se pronuncia", "Español", "Ejemplo"],
          [[f"**{w}**", p, s, f"*{ex}*"] for w, p, s, ex in VOCAB]),
    NOTE("Para describir lugares", "**big / small** grande / pequeño  ·  **old / new** viejo / nuevo  ·  **clean** limpio  ·  **large** amplio  ·  **colorful** colorido  ·  **friendly** amigable"),
    PB,

    H1("2. Lectura: My Old School and My New School"),
    P("Lee el texto dos veces. La primera vez, en silencio. La segunda, en voz alta o junto con el audio."),
    audio("02"),
    READ("My Old School and My New School", READING),
    H2("Chant: My Old School"),
    P("Escucha y repite. Fíjate en cómo suena la **-ed** final (lo explicamos en la Gramática C)."),
    audio("03"),
    POEM(CHANT),
    P("En el chant: walk**ed** /t/ · talk**ed** /t/ · play**ed** /d/ · plant**ed** /ɪd/ · paint**ed** /ɪd/"),
    PB,

    H1("3. Gramática del tema"),
    H2("A. Was / were (pasado de be)"),
    TABLE([3300, 3300, 3200], ["Afirmativa", "Negativa", "Pregunta"], [
        ["I / He / She / It **was** small.", "It **wasn't** big.", "**Was** it big?"],
        ["You / We / They **were** nervous.", "They **weren't** nervous.", "**Were** they nervous?"],
    ]),
    H2("B. Pasado simple"),
    P("Usamos el pasado simple para acciones **terminadas**: *last year, yesterday, in my old school*."),
    BULLETS("La mayoría de los verbos: **+ ed** → walk**ed**, play**ed**, talk**ed**.",
            "Terminan en -e: **+ d** → live**d**, move**d**.",
            "Consonante + y: **y → ied** → study → stud**ied**.",
            "Vocal corta + consonante: se **dobla** → stop → sto**pped**, plan → pla**nned**.",
            "Verbos irregulares (se aprenden de memoria): go → **went** · have → **had** · eat → **ate** · make → **made** · meet → **met** · see → **saw** · take → **took**."),
    TABLE([3300, 3300, 3200], ["Afirmativa", "Negativa", "Pregunta"], [
        ["We **planted** corn.", "We **didn't plant** rice.", "**Did** you **plant** corn?"],
        ["She **went** home.", "She **didn't go** home.", "**Did** she **go** home?"],
    ]),
    NOTE("Error común", "Después de **didn't** o **did**, el verbo vuelve a su forma base (sin -ed):",
         "✗ I didn't walk**ed**.  ✓ I didn't **walk**.     ✗ Did you went?  ✓ Did you **go**?"),
    H2("C. Pronunciación de la -ed final"),
    TABLE([2200, 4100, 3500], ["Sonido", "Cuándo", "Ejemplos"], [
        ["/t/", "después de p, k, s, sh, ch, f", "walked, talked, helped, watched"],
        ["/d/", "después de vocal o b, g, l, m, n, r, v, z", "played, moved, lived, studied"],
        ["/ɪd/ (una sílaba más)", "solo después de **t** o **d**", "planted, painted, wanted, needed"],
    ]),
    P("**Ojo:** *walked* se dice \"uokt\" (una sola sílaba), no \"uok-ed\". Solo se agrega una sílaba cuando el verbo termina en t o d."),
    H2("D. Used to (lo que hacías antes)"),
    P("**used to + verbo base** = algo que hacías antes y ahora ya no."),
    TABLE([4900, 4900], ["Ejemplo", "Significa"], [
        ["I **used to** walk to school.", "Antes caminaba a la escuela (ahora no)."],
        ["I **didn't use to** like Math.", "Antes no me gustaba Matemáticas."],
        ["**Did** you **use to** play soccer?", "¿Solías jugar fútbol?"],
    ]),
    H2("E. Comparativos y superlativos"),
    TABLE([2500, 2400, 2400, 2500], ["Regla", "Palabra", "Comparativo", "Superlativo"], [
        ["Palabra corta: + er / + est", "small", "small**er** than", "the small**est**"],
        ["Termina en -e: + r / + st", "large", "large**r** than", "the large**st**"],
        ["Vocal + consonante: se dobla", "big", "bi**gger** than", "the bi**ggest**"],
        ["Termina en -y: ier / iest", "noisy", "nois**ier** than", "the nois**iest**"],
        ["Palabra larga: more / most", "modern", "**more** modern than", "**the most** modern"],
        ["Irregulares", "good / bad", "**better** / **worse** than", "the **best** / the **worst**"],
    ]),
    NOTE("Error común", "✗ more big · ✓ **bigger**     ✗ bigger **that** · ✓ bigger **than**     ✗ the most quiet · ✓ **the quietest**"),
    H2("F. Will (planes y predicciones)"),
    P("*I **will** join the science club.*  ·  *We **won't** be late.*  ·  ***Will** you come? — Yes, I **will**. / No, I **won't**.*"),
    PB,

    H1("4. Listening (Escuchar)"),
    H2("Práctica: Luis and Rosa"),
    P("Escucha la conversación entre Luis y Rosa. **Primera vez:** solo escucha. **Segunda vez:** responde."),
    audio("04"),
    P("**Ejemplo:** Luis's previous school was small and ______.  →  **quiet**"),
    ITEMS("1. How many classrooms were there in Luis's previous school?"),
    OPTS("a) six", "b) seven", "c) sixteen"),
    ITEMS("2. Did his old school have a library?"),
    OPTS("a) Yes, it did.", "b) No, it didn't."),
    ITEMS("3. They planted ______________ and ______________ in the garden."),
    ITEMS("4. How does Luis go to school now?"),
    OPTS("a) He walks with his cousin.", "b) He takes the bus.", "c) His mom drives him."),
    ITEMS("5. Next month, Luis will join the ______________ club."),
    *test_blocks(TESTS["listening"], audio),
    PB,

    H1("5. Reading (Leer)"),
    H2("Práctica (texto: My Old School and My New School)"),
    P("**A. True or False.** Escribe T o F. Si es falso, corrige la oración."),
    P("**Ejemplo:** Luis's old school had a garden. → **T**"),
    ITEMS("1. Luis moved from Colón to Las Tablas. ______", "2. There were six classrooms in his old school. ______",
          "3. Luis's new school is smaller than his old school. ______", "4. Rosa helped Luis find his classroom. ______"),
    P("**B. Completa con palabras del texto.**"),
    ITEMS("1. Luis used to walk to school with his ______________.",
          "2. The ______________ is the noisiest place in the new school.",
          "3. At first, Luis was ______________ because he didn't know anyone."),
    P("**C. Cazador de -ed.** Busca en el texto 4 verbos en pasado con -ed. Escribe su sonido final: /t/, /d/ o /ɪd/."),
    P("**Ejemplo:** moved → **/d/**"),
    ITEMS("1. __________ → ______", "2. __________ → ______", "3. __________ → ______", "4. __________ → ______"),
    *test_blocks(TESTS["reading"], audio),
    PB,

    H1("6. Writing (Escribir)"),
    H2("Práctica"),
    P("**A. Completa con was o were.**"),
    P("**Ejemplo:** My old school ______ near a river. → **was**"),
    ITEMS("1. The teachers ______ very kind.", "2. ______ your classroom big?", "3. We ______ nervous on the first day.", "4. My best friend ______ in my class."),
    P("**B. Escribe el verbo en pasado simple.**"),
    ITEMS("1. Last year, I ______________ (move) to a new town.", "2. We ______________ (study) English every day.",
          "3. She ______________ (go) to school by bus.", "4. They ______________ (not / have) a library."),
    P("**C. Escribe el comparativo o el superlativo.**"),
    ITEMS("1. My new school is ______________ (big) than my old school.", "2. The library is ______________ (quiet) place in the school.",
          "3. Science is ______________ (interesting) than Math for me.", "4. My old playground was ______________ (good) than this one."),
    P("**D. Escribe sobre tu escuela anterior** (tu escuela primaria). Completa el modelo en tu cuaderno."),
    P("*My previous school was ________ and ________. I used to ________ at recess. My new school is ________ than my old school.*"),
    *test_blocks(TESTS["writing"], audio),
    PB,

    H1("7. Speaking (Hablar)"),
    H2("Práctica: escucha, repite y grábate"),
    P("**Paso 1.** Escucha cada oración y repítela en la pausa."),
    P("**Paso 2.** Grábate diciendo las mismas oraciones."),
    P("**Paso 3.** Compara tu grabación con el audio. ¿Dijiste *walked* en una sola sílaba? ¿Se oyó la sílaba extra en *planted*?"),
    audio("06"),
    ITEMS(*[f"{i+1}. {s}" for i, s in enumerate(SPEAK_MODELS)]),
    P("**Prepara tu descripción.** Escribe 5 oraciones comparando tu escuela anterior con tu escuela nueva. Practícala hasta decirla **sin leer**."),
    *test_blocks(TESTS["speaking"], audio),
    PB,

    H1("8. Mediation (Ayudar a otros a entender)"),
    P("En este tema vas a practicar **resumir lo que dijo otra persona** para alguien más. Cuando resumes, cambias **I → he / she** y **my → his / her**."),
    H2("Práctica"),
    P("**A. Resume para tu profesor.** Rosa presentó su escuela anterior. Escribe **2 oraciones** sobre lo que dijo."),
    NOTE("Presentación de Rosa", "*Hello! My old school was in Chitré. It was very old, but it had a big playground. I used to play baseball there every day. My best friend was Andrea. I miss her a lot.*"),
    P("**Ejemplo de inicio:** *Rosa's old school was in Chitré.* ...completa:"),
    LINES(2),
    P("**B. Simplifica.** Un estudiante nuevo no entiende este aviso. Escríbelo en **2 oraciones cortas**."),
    NOTE("Aviso", "*In this school, students are expected to arrive no later than 6:50 a.m., since the first period begins promptly at 7:00 a.m.*"),
    LINES(2),
    P("**C. Un letrero simple.** La biblioteca necesita un letrero para estudiantes que no leen bien inglés. Escribe un mensaje de **3 a 5 palabras** y haz un dibujo que lo explique."),
    P("**Ejemplo:** *Quiet, please!* + dibujo de un dedo sobre la boca."),
    LINES(1),
    *test_blocks(TESTS["mediation"], audio),
    PB,

    H1("¿Cómo me fue en el Tema 1.2?"),
    P("Anota tus puntajes. Te dicen qué repasar antes de una prueba."),
    TABLE([2600, 1600, 5600], ["Mini-test", "Puntaje", "Si tuviste menos de la mitad, repasa..."], [
        ["Listening", "___ / 6", "El Consejo de Listening (números *-teen* y *-ty*) y el audio 04 en velocidad lenta"],
        ["Reading", "___ / 6", "La lectura de Luis y cómo responder preguntas con *Why? — Because...*"],
        ["Writing", "___ / 10", "Gramática A (was/were), B (pasado y *didn't*) y E (comparativos)"],
        ["Speaking", "___ / 8", "Gramática C (pronunciación de -ed) y el audio 06"],
        ["Mediation", "___ / 8", "Cómo cambiar *I → he / she* al resumir"],
    ]),
    TABLE([6400, 1100, 1100, 1200], ["Puedo...", "Sí", "Casi", "Todavía no"], [
        ["describir mi escuela anterior con *was / were*", "☐", "☐", "☐"],
        ["usar el pasado simple y *used to*", "☐", "☐", "☐"],
        ["comparar dos escuelas (*bigger than, the most modern*)", "☐", "☐", "☐"],
        ["pronunciar la -ed: /t/, /d/, /ɪd/", "☐", "☐", "☐"],
        ["resumir lo que dijo un compañero", "☐", "☐", "☐"],
    ]),
    PB,

    H1("Respuestas del Tema 1.2"),
    P("Corrige **solo después de terminar**. Si te equivocaste, lee la explicación: ahí está lo que necesitas aprender."),
    H3("Listening — Práctica"),
    ITEMS("1. **a) six.** Luis dice: *There were only six classrooms.* (*Sixteen* sería 16.)",
          "2. **b) No, it didn't.** *Did you have a library? — No, we didn't.*",
          "3. **tomatoes** and **corn**.",
          "4. **c) His mom drives him.** Antes caminaba con su primo (*I used to walk*), pero la pregunta dice **now**.",
          "5. **science** club."),
    *answer_blocks(TESTS["listening"]),
    H3("Reading — Práctica"),
    ITEMS("A1. **F.** Luis moved **from Las Tablas to Colón** (al revés).   A2. **T.**",
          "A3. **F.** His new school is **bigger** than his old school.   A4. **T.**",
          "B1. **cousin**   B2. **cafeteria**   B3. **nervous**",
          "C. Puedes encontrar: moved /d/ · planted /ɪd/ · walked /t/ · talked /t/ · helped /t/. *Planted* lleva sílaba extra porque *plant* termina en t."),
    *answer_blocks(TESTS["reading"]),
    H3("Writing — Práctica"),
    ITEMS("A1. **were**  A2. **Was**  A3. **were**  A4. **was**   (*were* va con you / we / they y con plurales como *the teachers*.)",
          "B1. **moved** (termina en -e → +d)   B2. **studied** (y → ied)   B3. **went** (irregular)   B4. **didn't have** (después de *didn't*, verbo base)",
          "C1. **bigger** (se dobla la g)   C2. **the quietest**   C3. **more interesting** (palabra larga)   C4. **better** (irregular de *good*)",
          "D. Respuesta libre. Ejemplo: *My previous school was small and quiet. I used to play tag at recess. My new school is bigger than my old school.*"),
    *answer_blocks(TESTS["writing"]),
    H3("Mediation — ejemplos de respuesta"),
    ITEMS("Práctica A: *Rosa's old school was in Chitré. It was old, but it had a big playground, and she used to play baseball there.*",
          "Práctica B: *Arrive before 6:50. Classes start at 7:00.*",
          "Práctica C: *Quiet, please!* · *No food, please!* · *Return the books.*"),
    *answer_blocks(TESTS["mediation"]),
    PB,

    H1("Transcripciones de los audios del Tema 1.2"),
    P("Si no puedes escuchar un audio, pide a alguien que lo lea o léelo tú en voz alta. Úsalas también para revisar lo que no entendiste."),
    {"t": "transcripts"},
]
