# -*- coding: utf-8 -*-
"""Tema 2.2 — The Daily Habits of Animals"""
from common import *

THEME_ID = "2-2"
THEME_TITLE = "The Daily Habits of Animals"
SCENARIO = "Scenario 2: Panama's Wildlife"
PED, MAR, JAV, REP = "am_michael", "af_bella", "am_fenrir", "af_heart"
SPEAKERS = {PED: "Pedro", MAR: "Marta"}

VOCAB = [
    ("nocturnal", "nok-TÉR-nal", "nocturno (activo de noche)", "Owls are nocturnal. They are active at night."),
    ("diurnal", "dai-ÉR-nal", "diurno (activo de día)", "Toucans are diurnal. They are active during the day."),
    ("wake up", "UÉIK-ap", "despertarse", "Howler monkeys wake up early."),
    ("sleep", "SLIP", "dormir", "Bats sleep during the day."),
    ("hunt", "JANT", "cazar", "Owls hunt mice at night."),
    ("hide", "JAID", "esconderse", "Frogs hide under the leaves."),
    ("climb", "KLAIM", "trepar, subir", "Sloths climb down from the trees about once a week."),
    ("howl", "JAUL", "aullar", "Howler monkeys howl in the morning."),
    ("migrate", "MÁI-greit", "migrar", "Many hawks migrate over Panama in October."),
    ("feed on", "FID-on", "alimentarse de", "Hummingbirds feed on nectar."),
    ("observe", "ob-SÉRV", "observar", "We observe birds with binoculars."),
    ("insect", "ÍN-sekt", "insecto", "Bats eat insects at night."),
]

READING = [
    "Life in the rainforest never stops. At five thirty in the morning, the howler monkeys wake up and howl. Their loud call travels very far. People can hear it from kilometers away! Then they look for leaves and fruit to eat.",
    "During the day, toucans fly from tree to tree and eat fruit. Hummingbirds visit hundreds of flowers and feed on nectar. Sloths usually rest high in the trees. They move very slowly, and they climb down to the ground only about once a week.",
    "When the sun goes down, the rainforest changes. Bats leave their caves and hunt insects. Owls open their big eyes and hunt mice. Frogs sing near the river, and jaguars walk quietly through the forest. Nocturnal animals sleep during the day and look for food at night.",
    "Every animal has its own routine. Some animals are diurnal and some are nocturnal, but all of them are part of the rainforest.",
]
READING_BOOK = [p.replace("At five thirty", "At 5:30") for p in READING]

CHANT = [
    "Monkeys always howl at dawn,",
    "Sloths are usually slow and calm,",
    "Owls never sleep at night,",
    "Bats often hunt by pale moonlight.",
    "Nocturnal, diurnal, night and day,",
    "Every animal has its way!",
]

DIALOGUE = [
    (MAR, "Let's play Guess the Animal!"),
    (PED, "OK. How do we play?"),
    (MAR, "First, I choose an animal. I don't tell you the name! Then, I describe its habits. You have three chances to guess."),
    (PED, "Easy. Start!"),
    (MAR, "This animal is nocturnal. It sleeps during the day, and it hunts insects at night. It can fly."),
    (PED, "Is it an owl?"),
    (MAR, "No! Owls hunt mice. This animal sleeps upside down."),
    (PED, "Oh! It's a bat!"),
    (MAR, "Yes! Your turn."),
    (PED, "OK. This animal is diurnal. It's very small, and it feeds on nectar. It visits hundreds of flowers every day."),
    (MAR, "A hummingbird!"),
    (PED, "Correct!"),
]

TRIP = [
    "Last Saturday, our class went to the rainforest in Gamboa with our science teacher.",
    "We woke up very early and arrived at six in the morning. First, we heard the howler monkeys. They were really loud!",
    "Then we observed toucans eating fruit in a tall tree.",
    "At noon, it was very hot, and most animals were resting. Our guide showed us a sloth. It didn't move for one hour!",
    "In the afternoon, we saw hundreds of hawks in the sky. The guide said they migrate from North America to South America every October.",
    "We went home at five, before the bats came out. It was the best trip of the year!",
]

SPEAK_MODELS = [
    "Owls are nocturnal. They hunt at night.",
    "Howler monkeys always wake up early.",
    "Sloths usually move very slowly.",
    "Bats sleep during the day.",
    "First, choose an animal.",
    "Don't say its name!",
]

SPEAK_TEST_Q = [
    "Question one. Describe the daily routine of your favorite animal.",
    "Question two. Is your favorite animal nocturnal or diurnal? How do you know?",
    "Question three. What do you always do in the morning?",
    "Question four. Explain how to play a guessing game. Use first, then, and don't.",
    "Question five. What animal do you sometimes see near your home?",
]

TRACKS = [
    {"n": "01", "title": "Vocabulario clave", "instr": "Escucha cada palabra y su ejemplo. Repite en voz alta durante la pausa.",
     "segments": vocab_segments(VOCAB)},
    {"n": "02", "title": "Lectura: A Day in the Rainforest", "instr": "Escucha el texto mientras lo sigues con el dedo en tu libro.",
     "segments": [(REP, p, 1.0) for p in READING]},
    {"n": "03", "title": "Chant: Night and Day", "instr": "Escucha y repite. Fíjate en las palabras de frecuencia: always, usually, never, often.",
     "segments": [(NAR, l, 0.5) for l in CHANT]},
    {"n": "04", "title": "Listening — Práctica: Guess the Animal", "instr": "Escucha el diálogo dos veces. La primera vez, solo escucha. La segunda vez, responde.",
     "segments": [(v, t, 0.6) for v, t in DIALOGUE]},
    {"n": "05", "title": "Listening — Mini-test: A Trip to Gamboa", "instr": "Mini-test. Escucha dos veces como máximo y responde en tu libro.",
     "segments": [(JAV, t, 0.7) for t in TRIP]},
    {"n": "06", "title": "Speaking — Oraciones modelo", "instr": "Escucha cada oración y repítela en la pausa. Después grábate y compara.",
     "segments": [(NAR, s, 3.0) for s in SPEAK_MODELS]},
    {"n": "07", "title": "Speaking — Mini-test (examen oral)", "instr": "Activa la grabadora de tu celular. Responde cada pregunta en voz alta durante la pausa.",
     "segments": [(NAR, "Speaking test. Answer each question with complete sentences.", 2.0)] + [(NAR, q, 12.0) for q in SPEAK_TEST_Q]},
]
audio = audio_factory(THEME_ID, TRACKS)

SCHEDULE = TABLE([2000, 1900, 2900, 1700, 1300], ["Animal", "Wakes up", "Main activity", "Sleeps", "Type"], [
    ["howler monkey", "at 5:30 a.m.", "howls, eats leaves and fruit", "at night", "diurnal"],
    ["toucan", "early morning", "flies and eats fruit", "at night", "diurnal"],
    ["sloth", "it changes", "rests and eats leaves", "day and night", "both"],
    ["owl", "in the evening", "hunts mice", "during the day", "nocturnal"],
    ["bat", "in the evening", "hunts insects", "during the day", "nocturnal"],
])

BLOCKS = [
    {"t": "theme_cover", "scenario": SCENARIO, "theme": "Theme 2: " + THEME_TITLE, "es": "Los hábitos diarios de los animales",
     "goals": ["Describir la rutina de un animal con el presente simple: *The owl **hunts** at night.*",
               "Decir con qué frecuencia: *always, usually, often, sometimes, never.*",
               "Dar instrucciones para un juego: *First, **choose** a card. **Don't say** the name.*",
               "Leer un horario en una **tabla** y dividir palabras en **sílabas**: hum-ming-bird."]},

    H1("¿Te sientes perdido? Empieza aquí"),
    P("Si en clase no entendiste el tema, lee esta página primero. Aquí está **lo esencial** en una sola hoja."),
    H3("1. Las 10 palabras que más vas a escuchar"),
    TABLE([2200, 2700, 2200, 2700], ["Inglés", "Español", "Inglés", "Español"], [
        ["nocturnal", "nocturno", "hide", "esconderse"],
        ["diurnal", "diurno", "climb", "trepar"],
        ["wake up", "despertarse", "migrate", "migrar"],
        ["sleep", "dormir", "feed on", "alimentarse de"],
        ["hunt", "cazar", "insect", "insecto"],
    ]),
    H3("2. Las preguntas del tema y cómo responderlas"),
    TABLE([4900, 4900], ["Pregunta", "Respuesta"], [
        ["What **does** the owl **eat**?", "It **eats** mice."],
        ["When **do** bats **hunt**?", "They **hunt** at night."],
        ["**Does** the sloth **move** fast?", "No, it **doesn't**. It **moves** slowly."],
        ["How often **does** it climb down?", "About **once a week**."],
    ]),
    H3("3. Las reglas que más se preguntan en las pruebas"),
    P("**Presente simple:** con *it / he / she* el verbo lleva **-s** (*The owl hunt**s***). Con *they* no (*Owls hunt*)."),
    P("**Frecuencia:** always → usually → often → sometimes → never. Van **antes del verbo** (*Owls **never** sleep at night*), pero **después de be** (*Sloths **are usually** slow*)."),
    P("**Instrucciones:** empiezan con el verbo: ***Choose** a card. **Don't** say the name.*"),
    H3("4. Una descripción modelo"),
    P("*The owl is nocturnal. It sleeps during the day, and it usually hunts mice at night. It never hunts in the morning.*"),
    PB,

    H1("1. Vocabulario"),
    P("Escucha el audio, señala cada palabra y repítela en voz alta. La columna **Se pronuncia** es una ayuda aproximada; el audio es la pronunciación correcta."),
    audio("01"),
    TABLE([2100, 1800, 2400, 3500], ["Inglés", "Se pronuncia", "Español", "Ejemplo"],
          [[f"**{w}**", p, s, f"*{ex}*"] for w, p, s, ex in VOCAB]),
    NOTE("Animales del tema", "**owl** búho · **bat** murciélago · **toucan** tucán · **hummingbird** colibrí · **howler monkey** mono aullador · **sloth** perezoso · **hawk** gavilán · **frog** rana · **mouse / mice** ratón / ratones"),
    PB,

    H1("2. Lectura: A Day in the Rainforest"),
    P("Lee el texto dos veces. La primera vez, en silencio. La segunda, en voz alta o junto con el audio."),
    audio("02"),
    READ("A Day in the Rainforest", READING_BOOK),
    H2("Chant: Night and Day"),
    P("Escucha y repite. Fíjate en las **palabras de frecuencia** (lo explicamos en la Gramática A)."),
    audio("03"),
    POEM(CHANT),
    PB,

    H1("3. Gramática del tema"),
    H2("A. Presente simple y palabras de frecuencia"),
    P("Usamos el presente simple para los **hábitos**: lo que un animal hace todos los días."),
    TABLE([3200, 1400, 5200], ["Palabra", "Frecuencia", "Ejemplo"], [
        ["**always** (siempre)", "100 %", "Howler monkeys **always** wake up early."],
        ["**usually** (normalmente)", "80 %", "Sloths **usually** rest in the trees."],
        ["**often** (a menudo)", "60 %", "Bats **often** hunt near rivers."],
        ["**sometimes** (a veces)", "40 %", "Toucans **sometimes** eat insects."],
        ["**never** (nunca)", "0 %", "Owls **never** hunt in the morning."],
    ]),
    NOTE("¿Dónde va la palabra de frecuencia?", "**Antes del verbo:** *The owl **always hunts** at night.*",
         "**Después de be (is, are):** *Sloths **are usually** slow.*",
         "✗ The owl hunts always at night.  ✓ The owl **always hunts** at night."),
    H2("B. Expresiones de tiempo"),
    P("**in the morning** · **in the afternoon** · **in the evening** · **at night** · **at noon** · **during the day** · **every day** · **once a week** (una vez por semana) · **twice a day** (dos veces al día)"),
    H2("C. Preguntas sobre hábitos"),
    TABLE([4900, 4900], ["Pregunta", "Respuesta corta"], [
        ["**Does** the bat **sleep** during the day?", "Yes, it **does**."],
        ["**Does** the toucan **hunt** at night?", "No, it **doesn't**."],
        ["**Do** owls **eat** mice?", "Yes, they **do**."],
        ["**When does** the monkey **wake up**?", "It **wakes up** at 5:30."],
    ]),
    NOTE("Error común", "✗ Does the owl hunt**s**?  ✓ Does the owl **hunt**?     ✗ The bat sleep during the day.  ✓ The bat **sleeps** during the day."),
    H2("D. Instrucciones (para juegos y manualidades)"),
    P("Las instrucciones empiezan con el **verbo**, sin sujeto. Para ordenar los pasos usamos **First, Then, Next, Finally**."),
    TABLE([4900, 4900], ["Hacer", "No hacer"], [
        ["**Choose** a card.", "**Don't show** the card."],
        ["**Describe** the animal.", "**Don't say** its name."],
        ["**Guess** the animal.", "**Don't look** at the answer."],
    ]),
    P("*First, choose an animal card. Then, describe its habits. Next, your partner guesses. Finally, change roles.*"),
    H2("E. Sílabas y palabras compuestas"),
    TABLE([3300, 3300, 3200], ["Palabra", "Sílabas", "¿Compuesta?"], [
        ["hummingbird", "hum-ming-bird (3)", "Sí: humming + bird"],
        ["moonlight", "moon-light (2)", "Sí: moon + light"],
        ["toucan", "tou-can (2)", "No"],
        ["nocturnal", "noc-tur-nal (3)", "No"],
        ["insect", "in-sect (2)", "No"],
    ]),
    PB,

    H1("4. Listening (Escuchar)"),
    H2("Práctica: Guess the Animal"),
    P("Marta y Pedro juegan a adivinar animales. **Primera vez:** solo escucha. **Segunda vez:** responde."),
    audio("04"),
    P("**Ejemplo:** The name of the game is \"Guess the ______\".  →  **Animal**"),
    ITEMS("1. How many chances do you have to guess?"), OPTS("a) two", "b) three", "c) four"),
    ITEMS("2. Pedro's first answer is:"), OPTS("a) a bat", "b) an owl", "c) a toucan"),
    ITEMS("3. The bat sleeps ______________ ______________."),
    ITEMS("4. Pedro's animal is:"), OPTS("a) nocturnal", "b) diurnal"),
    ITEMS("5. What does the hummingbird feed on? ______________"),
    PB,
    H2("Mini-test de Listening"),
    TIP("Cuando el audio cuenta una historia en orden, fíjate en las palabras **First, Then, At noon, In the afternoon**: te dicen en qué parte del día pasó cada cosa."),
    P("Escucha a Javier contar el paseo de su clase a Gamboa. Puedes escuchar **dos veces como máximo**."),
    audio("05"),
    ITEMS("1. When did the class go to the rainforest?"), OPTS("a) last Saturday", "b) last Sunday", "c) last Friday"),
    ITEMS("2. What did they hear first?"), OPTS("a) toucans", "b) howler monkeys", "c) hawks"),
    ITEMS("3. Why were most animals resting at noon? ______________________________"),
    ITEMS("4. How long did the sloth stay still?"), OPTS("a) one minute", "b) one hour", "c) one day"),
    ITEMS("5. The hawks migrate every October.    True / False"),
    ITEMS("6. The students saw the bats.    True / False"),
    SCORE("Puntaje: ______ / 6"),
    PB,

    H1("5. Reading (Leer)"),
    H2("Práctica: el texto y un horario"),
    P("**A. True or False** (texto: *A Day in the Rainforest*). Escribe T o F. Si es falso, corrige la oración."),
    P("**Ejemplo:** Howler monkeys wake up at 5:30. → **T**"),
    ITEMS("1. Toucans eat fruit. ______", "2. Sloths climb down to the ground every day. ______",
          "3. Bats hunt insects at night. ______", "4. Nocturnal animals sleep at night. ______"),
    P("**B. Lee el horario y responde.** Primero lee los títulos de las columnas."),
    P("**Animal Schedules** (horario general de algunos animales del bosque)"),
    SCHEDULE,
    ITEMS("1. When does the howler monkey wake up? ______________",
          "2. What does the owl hunt? ______________",
          "3. Which two animals sleep during the day? ______________",
          "4. Is the toucan nocturnal? ______________"),
    P("**C. Sílabas.** Divide en sílabas y escribe cuántas tiene. Marca con ✓ las compuestas."),
    P("**Ejemplo:** moonlight → **moon-light (2) ✓**"),
    ITEMS("1. hummingbird → ______________", "2. monkey → ______________", "3. rainforest → ______________", "4. diurnal → ______________"),
    PB,
    H2("Mini-test de Reading"),
    TIP("Las preguntas de selección múltiple a veces tienen **dos opciones que aparecen en el texto**. Lee la oración completa para ver cuál responde exactamente la pregunta."),
    P("Lee el texto sobre las hormigas arrieras y responde."),
    READ("The Busy Leafcutter Ants", [
        "Leafcutter ants are some of the busiest animals in Panama's forests. You can see them on long trails, carrying pieces of green leaves. Each piece is bigger than the ant!",
        "But the ants don't eat the leaves. They take them to their nest under the ground. There, they use the leaves to grow a special fungus, and they eat the fungus.",
        "Some ants cut leaves, some carry them, and some clean the nest. Big ants protect the trail from predators. Leafcutter ants often work at night, but they sometimes work during the day too. A big nest can have millions of ants!",
    ]),
    ITEMS("1. Where is the ants' nest?"), OPTS("a) in the trees", "b) under the ground", "c) near the river"),
    ITEMS("2. Do the ants eat the leaves? ______________________________"),
    ITEMS("3. What do the big ants do? ______________________________"),
    ITEMS("4. Each piece of leaf is smaller than the ant.    True / False"),
    ITEMS("5. Leafcutter ants never work during the day.    True / False"),
    ITEMS("6. How many ants can live in a big nest?"), OPTS("a) hundreds", "b) thousands", "c) millions"),
    SCORE("Puntaje: ______ / 6"),
    PB,

    H1("6. Writing (Escribir)"),
    H2("Práctica"),
    P("**A. Ordena las palabras.**"),
    P("**Ejemplo:** hunt / owls / at night / always → **Owls always hunt at night.**"),
    ITEMS("1. wake up / howler monkeys / early / usually  →  ______________________________",
          "2. slow / sloths / always / are  →  ______________________________",
          "3. sleep / bats / never / at night  →  ______________________________"),
    P("**B. Completa con la forma correcta del verbo.**"),
    ITEMS("1. The toucan ______________ (eat) fruit.", "2. Owls ______________ (hunt) at night.",
          "3. ______________ the sloth move fast? — No, it ______________.", "4. The bat ______________ (not / sleep) at night."),
    P("**C. Instrucciones de una manualidad.** Completa los pasos con estos verbos: *cut · draw · glue · color*."),
    P("**Make a paper sloth:** First, ______ a sloth on a paper. Then, ______ it brown. Next, ______ it out. Finally, ______ it on a paper tree."),
    P("**D. Comenta el texto de un compañero.** Lee la descripción de Ana y escríbele **un comentario amable** de 1 o 2 oraciones."),
    NOTE("Descripción de Ana", "*My favorite animal is the owl. It is nocturnal. It hunts mice at night.*"),
    P("**Ejemplo:** *I like your information about the owl. Maybe you can add where it lives.*"),
    LINES(2),
    PB,
    H2("Mini-test de Writing"),
    TIP("En instrucciones, revisa que cada paso **empiece con un verbo** y que uses **First, Then, Finally** para ordenarlos."),
    P("**Parte A. Cada oración tiene un error. Escríbela correctamente.** (1 punto cada una)"),
    ITEMS("1. The owl hunt at night.  →  ______________________________",
          "2. Bats sleeps during the day.  →  ______________________________",
          "3. Sloths move always slowly.  →  ______________________________",
          "4. Does the toucan eats fruit?  →  ______________________________",
          "5. Not touch the animals!  →  ______________________________"),
    P("**Parte B.** Escribe las instrucciones del juego **Guess the Animal** en **4 o 5 pasos**. (5 puntos)"),
    LINES(5),
    P("**Revisa tus instrucciones.** Marca un punto por cada casilla:"),
    checklist("Cada paso empieza con un verbo (*Choose, Describe, Guess…*).", "Usé **First**, **Then** y **Finally**.",
              "Incluí una regla con **Don't**.", "Expliqué cómo se gana o cuántas oportunidades hay.", "Cada oración empieza con mayúscula y termina con punto."),
    SCORE("Puntaje: ______ / 10"),
    PB,

    H1("7. Speaking (Hablar)"),
    H2("Práctica: escucha, repite y grábate"),
    P("**Paso 1.** Escucha cada oración y repítela en la pausa."),
    P("**Paso 2.** Grábate diciendo las mismas oraciones."),
    P("**Paso 3.** Compara tu grabación con el audio. ¿Pronunciaste la -s de *hunts* y *moves*?"),
    audio("06"),
    ITEMS(*[f"{i+1}. {s}" for i, s in enumerate(SPEAK_MODELS)]),
    P("**Prepara tu juego.** Elige 3 animales y escribe 3 pistas para cada uno (*It is nocturnal. It hunts mice...*). Juega con alguien de tu casa: tú das las pistas en inglés."),
    PB,
    H2("Mini-test de Speaking (examen oral)"),
    TIP("Para explicar las reglas de un juego, ordénalas: **First…, Then…, Finally…** Así quien te escucha (o te evalúa) te sigue fácilmente."),
    P("Activa la grabadora de tu celular y luego reproduce el audio. Responde cada pregunta en voz alta **durante la pausa**."),
    audio("07"),
    P("Después, escucha tu grabación y marca un punto por cada casilla:"),
    checklist("Pregunta 1: describí al menos 2 hábitos", "Pregunta 2: dije **nocturnal** o **diurnal** y por qué",
              "Pregunta 3: usé **always**", "Pregunta 4: usé **First**, **Then** y **Don't**", "Pregunta 5 con oración completa",
              "Pronuncié la -s con *it / he / she*", "Hablé sin leer", "No usé español"),
    SCORE("Puntaje: ______ / 8"),
    PB,

    H1("8. Mediation (Ayudar a otros a entender)"),
    P("En este tema vas a practicar **explicar instrucciones con gestos y dibujos**, y convertir instrucciones largas en pasos cortos."),
    H2("Práctica"),
    P("**A. Gestos del salón.** Escribe la instrucción en inglés que corresponde a cada gesto."),
    TABLE([4900, 4900], ["Gesto", "Instrucción en inglés"], [
        ["Dedo índice sobre los labios", "**Ejemplo:** *Be quiet.*"],
        ["Mano levantada", ""],
        ["Mano detrás de la oreja", ""],
        ["Señalar los ojos y luego la pizarra", ""],
    ]),
    P("**B. Explica en español.** Tu hermano menor no entiende estas reglas en inglés. Escríbele en español qué debe hacer."),
    NOTE("Reglas", "*1. Choose a card. 2. Don't show it. 3. Describe the animal's habits. 4. Your partner guesses.*"),
    LINES(2),
    P("**C. Simplifica.** Convierte esta instrucción en **2 pasos cortos**."),
    NOTE("Instrucción", "*Before you start writing your animal description, it is important that you look carefully at the pictures in the chart on page 10.*"),
    LINES(2),
    PB,
    H2("Mini-test de Mediation"),
    TIP("Divide las instrucciones largas en **pasos numerados**. Cada paso, una sola acción."),
    P("**Parte A.** Convierte esta instrucción larga en **3 pasos cortos y numerados**, y haz un dibujo pequeño para cada paso."),
    NOTE("Instrucción", "*For today's activity, each student will select one animal card from the box, then write three sentences describing the animal's daily habits without mentioning its name, and finally read the description aloud so that classmates can guess the animal.*"),
    LINES(3),
    P("Marca un punto por cada casilla:"),
    checklist("Paso 1 correcto (tomar una tarjeta)", "Paso 2 correcto (escribir 3 oraciones sobre sus hábitos)",
              "Incluí la regla: no escribir el nombre (*Don't…*)", "Paso 3 correcto (leer en voz alta; los demás adivinan)", "Hice un dibujo para cada paso"),
    P("**Parte B.** Un visitante que solo habla inglés llega a tu salón. Traduce este cartel en **inglés simple**."),
    NOTE("Cartel", "Levanta la mano para hablar y no corras en el salón."),
    LINES(2),
    P("Marca un punto por cada casilla:"),
    checklist("Escribí *Raise your hand*.", "Escribí *to talk / to speak*.", "Escribí *Don't run in the classroom*."),
    SCORE("Puntaje: ______ / 8"),
    PB,

    H1("¿Cómo me fue en el Tema 2.2?"),
    P("Anota tus puntajes. Te dicen qué repasar antes de una prueba."),
    TABLE([2600, 1600, 5600], ["Mini-test", "Puntaje", "Si tuviste menos de la mitad, repasa..."], [
        ["Listening", "___ / 6", "El Consejo de Listening (First, Then, At noon) y el audio 04 en velocidad lenta"],
        ["Reading", "___ / 6", "El horario *Animal Schedules* y el Consejo de Reading"],
        ["Writing", "___ / 10", "Gramática A (frecuencia), C (preguntas con *does*) y D (instrucciones)"],
        ["Speaking", "___ / 8", "El audio 06 y el juego con tus 3 animales"],
        ["Mediation", "___ / 8", "Cómo dividir una instrucción larga en pasos"],
    ]),
    TABLE([6400, 1100, 1100, 1200], ["Puedo...", "Sí", "Casi", "Todavía no"], [
        ["describir la rutina de un animal con el presente simple", "☐", "☐", "☐"],
        ["usar *always, usually, often, sometimes, never*", "☐", "☐", "☐"],
        ["dar instrucciones para un juego (*First, Then, Don't*)", "☐", "☐", "☐"],
        ["leer un horario en una tabla", "☐", "☐", "☐"],
        ["dividir instrucciones largas en pasos cortos", "☐", "☐", "☐"],
    ]),
    PB,

    H1("Respuestas del Tema 2.2"),
    P("Corrige **solo después de terminar**. Si te equivocaste, lee la explicación: ahí está lo que necesitas aprender."),
    H3("Listening — Práctica"),
    ITEMS("1. **b) three.** *You have three chances to guess.*",
          "2. **b) an owl.** *Is it an owl? — No! Owls hunt mice.*",
          "3. **upside down** (boca abajo).",
          "4. **b) diurnal.** *This animal is diurnal.*",
          "5. **nectar.** *It feeds on nectar.*"),
    H3("Listening — Mini-test"),
    ITEMS("1. **a) last Saturday.**",
          "2. **b) howler monkeys.** *First, we heard the howler monkeys.* La palabra **First** te da la respuesta.",
          "3. **Because it was very hot.**",
          "4. **b) one hour.** *It didn't move for one hour!*",
          "5. **True.** *They migrate from North America to South America every October.*",
          "6. **False.** *We went home at five, **before** the bats came out.* Se fueron antes de que salieran."),
    H3("Reading — Práctica"),
    ITEMS("A1. **T.**   A2. **F.** They climb down **about once a week**.   A3. **T.**",
          "A4. **F.** Nocturnal animals sleep **during the day** (de noche buscan comida).",
          "B1. **At 5:30 a.m.**   B2. **Mice.**   B3. **The owl and the bat.**   B4. **No, it isn't.** It's diurnal.",
          "C1. **hum-ming-bird (3) ✓**   C2. **mon-key (2)**   C3. **rain-for-est (3) ✓**   C4. **di-ur-nal (3)**"),
    H3("Reading — Mini-test"),
    ITEMS("1. **b) under the ground.** *Their nest under the ground.*",
          "2. **No, they don't.** They eat a fungus (un hongo).",
          "3. **They protect the trail from predators.**",
          "4. **False.** *Each piece is **bigger** than the ant.*",
          "5. **False.** *They **sometimes** work during the day too.* **Never** sería 0 %, y el texto dice *sometimes*.",
          "6. **c) millions.**"),
    H3("Writing — Práctica"),
    ITEMS("A1. **Howler monkeys usually wake up early.**   A2. **Sloths are always slow.** (después de *are*)   A3. **Bats never sleep at night.**",
          "B1. **eats**   B2. **hunt** (*owls* = they, sin -s)   B3. **Does** … **doesn't**   B4. **doesn't sleep**",
          "C. **draw** · **color** · **cut** · **glue**  (First, draw… Then, color… Next, cut… Finally, glue…)",
          "D. Respuesta libre. Ejemplo: *Great description! I like the information about the owl's food. Maybe you can add where it sleeps.*"),
    H3("Writing — Mini-test, Parte A"),
    ITEMS("1. The owl **hunts** at night. (*the owl* = it → -s)",
          "2. Bats **sleep** during the day. (*bats* = they → sin -s)",
          "3. Sloths **always move** slowly. (la palabra de frecuencia va antes del verbo)",
          "4. Does the toucan **eat** fruit? (después de *does*, verbo sin -s)",
          "5. **Don't touch** the animals! (la negación en instrucciones es *Don't*)"),
    P("**Parte B, ejemplo de respuesta:** *First, choose an animal card. Don't show it to your partner. Then, describe the animal's habits. Your partner has three chances to guess. Finally, change roles.*"),
    H3("Mediation — ejemplos de respuesta"),
    ITEMS("Práctica A: *Raise your hand.* · *Listen.* · *Look at the board.*",
          "Práctica B: *Escoge una tarjeta, no se la enseñes a nadie, describe cómo vive el animal y tu compañero adivina cuál es.*",
          "Práctica C: *1. Look at the pictures on page 10. 2. Write your description.*",
          "Mini-test A: *1. Take an animal card. 2. Write 3 sentences about its habits. Don't write its name. 3. Read your sentences. Your classmates guess.*",
          "Mini-test B: *Raise your hand to talk. Don't run in the classroom.*"),
    PB,

    H1("Transcripciones de los audios del Tema 2.2"),
    P("Si no puedes escuchar un audio, pide a alguien que lo lea o léelo tú en voz alta. Úsalas también para revisar lo que no entendiste."),
    {"t": "transcripts"},
]
